# Site settings
name: Adam Saegebarth
title: Adam Saegebarth
email: adam@saegey.com
description: "Loves to Code"
baseurl: "/saegey.github.io"
url: "http://saegey.com"
brand: AS
# Build settings
markdown: kramdown
permalinks: pretty